@echo off
echo Demarrage de StockProtec...
echo.
echo Installation des dépendances...
call npm install

echo.
echo Construction de l'interface utilisateur...
call npm run build

echo.
echo Demarrage du serveur API...
call npm run server
