@echo off
echo Demarrage de StockProtec avec SQLite...
echo.
echo Installation des dépendances...
call npm install

echo.
echo Demarrage du serveur API et de l'interface avec SQLite...
call npm run dev:all
